import { Type } from 'class-transformer';
import { IsArray, IsNumber, IsOptional, IsString, IsUUID, ValidateNested } from 'class-validator';

// 점검 상태
export const InspectionItemStatus = ['pass', 'normal', 'bad'];

// 외관 점검 항목 이름
export const ExteriorTitle = [
  { titleEn: 'CAR TILT CHECK', titleLo: 'ກວດເຊັດການອຽງ(ງ່ຽງ) ຂອງລົດ' },
  { titleEn: 'KEY & REMOTE', titleLo: 'ກະແຈ ແລະ ລິໂໝດ' },
  { titleEn: 'FRONT BUMPER', titleLo: 'ກັນຊົນໜ້າ' },
  { titleEn: 'LAMP ASSY-HEAD,LH', titleLo: 'ຕາໜ້າ ຊ້າຍ' },
  { titleEn: 'LAMP ASSY-HEAD,RH', titleLo: 'ຕາໜ້າຂວາ' },
  { titleEn: 'LAMP ASSY-FRONT FOG,LH', titleLo: 'ຕາສະປອດໄລ້ ຊ້າຍ' },
  { titleEn: 'COVER-FR BUMPER FOG LAMP,LH', titleLo: 'ໂກບຕາສະປອດໄລ້ ຊ້າຍ' },
  { titleEn: 'LAMP ASSY-FRONT FOG,RH', titleLo: 'ຕາສະປອດໄລ້ ຂວາ' },
  { titleEn: 'COVER-FR BUMPER FOG LAMP,RH', titleLo: 'ໂກບຕາສະປອດໄລ້ ຂວາ' },
  { titleEn: 'SENSOR ASSY-PARKING FR', titleLo: 'ເຊັນເຊີກັນຊົນໜ້າ' },
  { titleEn: 'HEADLAMP WASHER,LH', titleLo: 'ຫົວສີດນ້ຳລ້າງຕາໜ້າຊ້າຍ' },
  { titleEn: 'HEADLAMP WASHER,RH', titleLo: 'ຫົວສີດນ້ຳລ້າງຕາໜ້າຂວາ' },
  { titleEn: 'GRILLE ASSY-RADIATOR', titleLo: 'ຕາໜາງກັນຊົນ' },
  { titleEn: 'GRILLE-FRONT BUMPER CTR', titleLo: 'ຕາໜາງກັນຊົນໂຕກາງ' },
  { titleEn: 'COVER-FR BUMPER,LWR', titleLo: 'ກັນຊົນໜ້າໂຕລຸ່ມ' },
  { titleEn: 'MIRROR ASSY-OUTSIDE RR VIEW,LH', titleLo: 'ແວ່ນແຍ່ງຂ້າງຊ້າຍ' },
  { titleEn: 'FRONT PANEL-FENDER,LH', titleLo: 'ແກ້ມຫນ້າຊ້າຍ' },
  { titleEn: 'GUARD ASSY-FRONT WHEEL,LH', titleLo: 'ບັງຕົມໂຄ້ງໜ້າຊ້າຍ' },
  { titleEn: 'GARNISH ASSY-FNDR SIDE,LH', titleLo: 'ໂກບໂຄງລໍ້ລົດໜ້າຊ້າຍ' },
  { titleEn: 'A PILLAR (LH)', titleLo: 'ເສົາປະຕູໜ້າຊ້າຍ' },
  { titleEn: 'PANEL ASSY-FRONT DOOR,LH', titleLo: 'ປະຕູໜ້າຊ້າຍ' },
  { titleEn: 'GRIP-FRONT DOOR OUTSIDE,LH', titleLo: 'ມືໄຂປະຕູໜ້າຊ້າຍ ນອກ' },
  { titleEn: 'GLASS ASSY-WINDSHIELD', titleLo: 'ກະຈົກໜ້າ' },
  { titleEn: 'BLADE ASSY-WIPER', titleLo: 'ຟອຍປັດນ້ຳຝົນ' },
  { titleEn: 'ARM ASSY-W/SHLD WPR', titleLo: 'ຂາປັດນ້ຳຝົນ' },
  { titleEn: 'B PILLAR (LH)', titleLo: 'ເສົາປະຕູກາງ ຊ້າຍ' },
  { titleEn: 'PANEL ASSY-REAR DOOR,LH', titleLo: 'ປະຕູຫຼັງຊ້າຍ' },
  { titleEn: 'GARNISH ASSY-FR DR SIDE,LH', titleLo: 'ແຂບປະຕູໜ້າຊ້າຍ' },
  { titleEn: 'GRIP-REAR DOOR OUTSIDE,LH', titleLo: 'ມືໄຂປະຕູນອກຫຼັງຊ້າຍ' },
  { titleEn: 'SLIDING DOOR, LH', titleLo: 'ປະຕູເລື່ອນຊ້າຍ' },
  { titleEn: 'AUTOMATIC SLIDING DOOR MOTOR LH', titleLo: 'ຊຸດມໍເຕີໄຂປະຕູເລື່ອນຊ້າຍ' },
  { titleEn: 'ROOF', titleLo: 'ຫຼັງຄາ' },
  { titleEn: 'C PILLAR (LH)', titleLo: 'ເສົາປະຕູຫຼັງຊ້າຍ' },
  { titleEn: 'REAR PANEL-FENDER,LH', titleLo: 'ອກ້ມປະຕູຫຼັງຊ້າຍ (ແກ້ມຫຼັງ)' },
  { titleEn: 'GUARD ASSY-REAR WHEEL,LH', titleLo: 'ບັງຕົມໂຄ້ງຫຼັງຊ້າຍ' },
  { titleEn: 'GARNISH ASSY-RR DR SIDE LH', titleLo: 'ແຂບປະຕູຫຼັງຊ້າຍ' },
  { titleEn: 'GARNISH ASSY-QTR SIDE,LH', titleLo: 'ແຂບປະຕູຫຼັງໂຕສຸດທ້າຍ ຊ້າຍ' },
  { titleEn: 'SIDE STEP(LH)', titleLo: 'ບັນໃດ ຊ້າຍ' },
  { titleEn: 'STEP ASSY-RR BUMPER', titleLo: 'ໂກບຢຽບຂື້ນກັນຊົນຫຼັງ' },
  { titleEn: 'PANEL ASSY-TAIL GATE', titleLo: 'ຝາກະໂປງຫຼັງ' },
  { titleEn: 'GARNISH ASSY-TAIL GATE', titleLo: 'ໂກບມືໄຂຝາກະໂປ່ງຫຼັງ' },
  { titleEn: 'CAMERA ASSY-BACK VIEW', titleLo: 'ກ້ອງຫຼັງ' },
  { titleEn: 'POWER LATCH ASSY-PWR T/GATE', titleLo: 'ສະວິກໄຂຝາກະໂປງຫຼັງ' },
  { titleEn: 'TRIM ASSY-LUGG FLR BOX', titleLo: 'ຜ້າປົກຢາງສະກົ້ວ' },
  { titleEn: 'TRIM ASSY-LUGGAGE SIDE LH', titleLo: 'ໂກບໃນບ່ອນມ້ຽນຢາງສະກົ້ວຊ້າຍ' },
  { titleEn: 'TRIM ASSY-LUGGAGE SIDE RH', titleLo: 'ໂກບໃນບ່ອນມ້ຽນຢາງສະກົ້ວຂວາ' },
  { titleEn: 'SPEAKER BOARD', titleLo: 'ຖາດວາງເຄື່ອງທາງຫຼັງ' },
  { titleEn: 'PANEL ASSY-BACK', titleLo: 'ກວດໂຄງຕາຫຼັງ (ເກີດອຸບັດຕິເຫດບໍ່)' },
  { titleEn: 'SPARE TIRE', titleLo: 'ຢາງສກົ້ວ' },
  { titleEn: 'OVM TOOL', titleLo: 'ເຄື່ອງມື' },
  { titleEn: 'PANEL ASSY-TAIL GATE TRIM', titleLo: 'ໂກບຝາກະໂປງຫຼັງ' },
  { titleEn: 'LIFTER ASSY-TAIL GATE', titleLo: 'ຊົກອັບຝາກະໂປງຫຼັງ' },
  { titleEn: 'LAMP ASSY-LICENSE PLATE', titleLo: 'ໄຟແຍງປ້າຍ' },
  { titleEn: 'COVER-RR BUMPER', titleLo: 'ກັນຊົນຫຼັງ' },
  { titleEn: 'COVER-RR BUMPER LWR', titleLo: 'ໂກບກ້ອງກັນຊົນຫຼັງ' },
  { titleEn: 'SENSOR ASSY-ULTRASONIC BWS', titleLo: 'ເຊັນເຊີຖອຍ' },
  { titleEn: 'GLASS ASSY-REAR WINDOW', titleLo: 'ກະຈົກຫຼັງ' },
  { titleEn: 'FUEL CAP', titleLo: 'ຝາອັດຖັງນ້ຳມັນ' },
  { titleEn: 'SWITCH ASSY-F/FILLER OPENER', titleLo: 'ສະວີກເປີດຖັງນ້ຳມັນ' },
  { titleEn: 'OPENER ASSY-FUEL FILLER DOOR', titleLo: 'ໂກບອັດຝາຖັງນ້ຳມັນ' },
  { titleEn: 'LAMP ASSY-REAR COMB INSIDE,LH', titleLo: 'ຕາຫຼັງໃນ ຊ້າຍ' },
  { titleEn: 'LAMP ASSY-REAR COMB OUTSIDE,LH', titleLo: 'ຕາຫຼັງນອກ ຊ້າຍ' },
  { titleEn: 'LAMP ASSY-REAR COMB INSIDE,RH', titleLo: 'ຕາຫຼັງໃນ ຂວາ' },
  { titleEn: 'LAMP ASSY-REAR COMB OUTSIDE,RH', titleLo: 'ຕາຫຼັງນອກ ຂວາ' },
  { titleEn: 'BRAKE LAMP', titleLo: 'ຕາໄຟເບກ' },
  { titleEn: 'BACKWARD LAMP', titleLo: 'ຕາໄຟຖອຍ' },
  { titleEn: 'FOG LAMP RR', titleLo: 'ຕາໄຟສະທ້ອນຫຼັງ' },
  { titleEn: 'EMBLEM', titleLo: 'ໂລໂກ້' },
  { titleEn: 'DECK ASSY-REAR', titleLo: 'ຝາຂ້າງ' },
  { titleEn: 'PANEL DECK', titleLo: 'ແຜ່ນໂຕນ' },
  { titleEn: 'BOX ASSY-TOOL', titleLo: 'ຕູ້ເຄື່ອງມື' },
  { titleEn: 'ANTENNA', titleLo: 'ຫຼັກອັງແຕນ' },
  { titleEn: 'REAR PANEL-FENDER,RH', titleLo: 'ແກ້ມປະຕູຫຼັງ ຂວາ' },
  { titleEn: 'GUARD ASSY-REAR WHEEL,RH', titleLo: 'ບັງຕົມໂຄ້ງຫຼັງຂວາ' },
  { titleEn: 'GARNISH ASSY-RR DR SIDE,RH', titleLo: 'ແຂບປະຕູເລື່ອນຂວາ' },
  { titleEn: 'C PILLAR (RH)', titleLo: 'ເສົາປະຕູຫຼັງຂວາ' },
  { titleEn: 'SLIDING DOOR, RH', titleLo: 'ປະຕູເລື່ອນຂວາ' },
  { titleEn: 'AUTOMATIC SLIDING DOOR MOTOR RH', titleLo: 'ຊຸດມໍເຕີໄຂປະຕູເລື່ອນຂວາ' },
  { titleEn: 'PANEL ASSY-REAR DOOR,RH', titleLo: 'ປະຕູຫຼັງຂວາ' },
  { titleEn: 'GARNISH ASSY-QTR SIDE,RH', titleLo: 'ແຂບປະຕູຫຼັງໂຕສຸດທ້າຍ ຂວາ' },
  { titleEn: 'GRIP-REAR DOOR OUTSIDE,RH', titleLo: 'ມືໄຂປະຕູຫຼັງຂວາ ນອກ' },
  { titleEn: 'B PILLAR (RH)', titleLo: 'ເສົາປະຕູກາງ ຂວາ' },
  { titleEn: 'PANEL ASSY-FRONT DOOR,RH', titleLo: 'ປະຕູໜ້າຂວາ' },
  { titleEn: 'GRIP-FRONT DOOR OUTSIDE,RH', titleLo: 'ມືໄຂປະຕູໜ້າຂວາ ນອກ' },
  { titleEn: 'GARNISH ASSY-FR DR SIDE RH', titleLo: 'ແຂບຂ້າງປະຕູໜ້າ ຂວາ' },
  { titleEn: 'SIDE STEP(RH)', titleLo: 'ບັນໃດ ຂວາ' },
  { titleEn: 'MIRROR ASSY-OUTSIDE RR VIEW,RH', titleLo: 'ແວ່ນແຍ່ງຂ້າງຂວາ' },
  { titleEn: 'A PILLAR (RH)', titleLo: 'ເສົາປະຕູໜ້າຂວາ' },
  { titleEn: 'FRONT PANEL-FENDER,RH', titleLo: 'ແກ້ມໜ້າຂ້າງຂວາ' },
  { titleEn: 'GUARD ASSY-FRONT WHEEL,RH', titleLo: 'ບັງຕົມໜ້າຂວາ' },
  { titleEn: 'GARNISH ASSY-FNDR SIDE,RH', titleLo: 'ແຂບຂ້າງໜ້າຂວາ' },
  { titleEn: 'HOOD', titleLo: 'ຝາກະໂປງໜ້າ' },
  { titleEn: 'LIFTER-HOOD', titleLo: 'ຊົກອັບຝາກະໂປງໜ້າ' },
  { titleEn: 'LATCH ASSY-HOOD', titleLo: 'ຊຸດລ໋ອກຝາກະໂປງໜ້າ' },
  { titleEn: 'CABLE ASSY-HOOD LATCH', titleLo: 'ສາຍດືງຝາກະໂປງໜ້າ' },
  { titleEn: 'PAD ASSY-HOOD INSULATION', titleLo: 'ແຜ່ນກັນຄວາມຮ້ອນຝາກະໂປ່ງໜ້າ' },
  { titleEn: 'HANDLE ASSY-HOOD LATCH RELEASE', titleLo: 'ມືໄຂຝາກະໂປງໜ້າ' },
  { titleEn: 'RACK ASSY-ROOF', titleLo: 'ຄານຫຼັງຄາ' },
  { titleEn: 'SPOILER ASSY-RR', titleLo: 'ສະປອຍເລີ' },
  { titleEn: 'W/STRIP ASSY-FR DR BELT O/S', titleLo: 'ຄີ້ວປະຕູນອກ-ໜ້າ' },
  { titleEn: 'W/STRIP ASSY-RR DR BELT O/S', titleLo: 'ຄີວປະຕູນອກ-ຫຼັງ' },
  { titleEn: 'HINGE ASSY-HOOD', titleLo: 'ບັນພັບຝາກະໂປງໜ້າ' },
];

// 내부 점검 항목 이름
export const InteriorTitle = [
  { titleEn: 'BUTTON START SYSTEM', titleLo: 'ປຸ່ມກົດສະຕ໋າດ' },
  { titleEn: 'ENGINE STARTING', titleLo: 'ກວດເຊັກການຕິດເຄື່ອງຈັກລົດ' },
  { titleEn: 'Engine Acceleration', titleLo: 'ກວດເຊັກຄັນເລັ່ງ' },
  { titleEn: 'ENGINE NOISE', titleLo: 'ກວດເຊັກຟັງສຽງສະພາບເຄື່ອງຈັກ' },
  { titleEn: 'Meter And Gauges Operation', titleLo: 'ກວດໂມງວັດກົງເຕີ' },
  { titleEn: 'CLUTCH GAP', titleLo: 'ກວດເຊັກການເຮັດວຽກຂາຢຽບຄາດ' },
  { titleEn: 'BRAKE GAP', titleLo: 'ກວດເຊັກການເຮັດວຽກຂາຢຽບເບກ' },
  { titleEn: 'HORN', titleLo: 'ແກ' },
  { titleEn: 'CLUSTER ASSY', titleLo: 'ໜ້າປັດກົງເຕີ' },
  { titleEn: 'PANEL ASSY-CLUSTER FACIA', titleLo: 'ໂກບກົງເຕີ' },
  { titleEn: 'PANEL ASSY-CENTER FACIA,UPR', titleLo: 'ໜ້າກາກຊີດີ' },
  { titleEn: 'CRASH PAD ASSY-MAIN', titleLo: 'ຕັບໂບ້' },
  { titleEn: 'GLOVE BOX ASSY', titleLo: 'ກ່ອງໃສເກະສານ' },
  { titleEn: 'ASH TRAY ASSY', titleLo: 'ກ່ອງເຂ່ຍຂີ້ກອກຢາ' },
  { titleEn: 'SUNVISOR ASSY', titleLo: 'ບັງແດດ' },
  { titleEn: 'VANITY MIRROR & LIGHT', titleLo: 'ແວ່ນແຍງຫ້ອງຂັບ' },
  { titleEn: 'HANDLE ASSY-ROOF ASSIST FRONT(LH)', titleLo: 'ມືຈ່ອງ ເພດານຊ້າຍ' },
  { titleEn: 'HANDLE ASSY-ROOF ASSIST FRONT(RH)', titleLo: 'ມືຈ່ອງ ເພດານຂວາ' },
  { titleEn: 'AUDIO ASSY', titleLo: 'ວິທະຍຸ' },
  { titleEn: 'SPEAKERS', titleLo: 'ລຳໂພງ' },
  { titleEn: 'WIRELESS A CHARGE', titleLo: 'ຊ່ອງສາກໂທລະສັບ' },
  { titleEn: 'DUCT ASSY-CTR AIR VENT,LH', titleLo: 'ຊ່ອງແອກາງ ຊ້າຍ' },
  { titleEn: 'DUCT ASSY-CTR AIR VENT,RH', titleLo: 'ຊ່ອງແອກາງ ຂວາ' },
  { titleEn: 'DUCT ASSY-SIDE AIR VENT,LH', titleLo: 'ຊ່ອງແອຊ້າຍ' },
  { titleEn: 'DUCT ASSY-SIDE AIR VENT,RH', titleLo: 'ຊ່ອງແອ ຂວາ' },
  { titleEn: 'SWITCH ASSY-P/WDO MAIN', titleLo: 'ສະວີກກົດແວ່ນໜ້າຊ້າຍ (ສະວິກລວມ)' },
  { titleEn: 'HANDLE ASSY-DOOR INSIDE,LH', titleLo: 'ມືໄຂປະຕູໃນຊ້າຍ' },
  { titleEn: 'HANDLE ASSY-DOOR INSIDE,RH', titleLo: 'ມືໄຂປະຕູໃນ ຂວາ' },
  { titleEn: 'FRONT DOOR TRIM,LH', titleLo: 'ໂກບປະຕູໜ້າ ຊ້າຍ' },
  { titleEn: 'FRONT DOOR TRIM,RH', titleLo: 'ໂກບປະຕູໜ້າ ຂວາ' },
  { titleEn: 'REAR DOOR TRIM,LH', titleLo: 'ໂກບປະຕູຫຼັງ ຊ້າຍ' },
  { titleEn: 'REAR DOOR TRIM,RH', titleLo: 'ໂກບປຕູຫຼັງ ຂວາ' },
  { titleEn: 'ARMREST ASSY-CONSOLE', titleLo: 'ບ່ອນພັກແຂນ' },
  { titleEn: 'COVER ASSY-CONSOLE RR', titleLo: 'ໂກບບ່ອນພັກແຂນທາງຫຼັງ' },
  { titleEn: 'COVER-CONSOLE INDICATOR', titleLo: 'ໂກບປົກຫົວຄັນເກຍ' },
  { titleEn: 'SHROUD ASSY', titleLo: 'ອຸ້ມລມຈັກ' },
  { titleEn: 'KNOB ASSY-GEAR SHIFT LEVER', titleLo: 'ຫົວຄັນເກຍ' },
  { titleEn: 'BOOT ASSY-SHIFT LEVER', titleLo: 'ຜ້າຫຸ້ມຄັນເກຍ' },
  { titleEn: 'CABLE ASSY-TM LEVER', titleLo: 'ສາຍຄັນເກຍ' },
  { titleEn: 'COVER ASSY-PARKING BRAKE', titleLo: 'ໂກບເບກມື' },
  { titleEn: 'HEADLINING ASSY', titleLo: 'ເພດານ' },
  { titleEn: 'S/BELT ASSY-FR LH', titleLo: 'ສາຍເຂັມຂັດໜ້າຊ້າຍ' },
  { titleEn: 'S/BELT ASSY-FR RH', titleLo: 'ສາຍເຂັມຂັດໜ້າຂວາ' },
  { titleEn: 'MIRROR ASSY-REAR VIEW INSIDE', titleLo: 'ແວ່ນແຍ່ງຫ້ອງຂັບ' },
  { titleEn: 'CONTROL ASSY-HEATER', titleLo: 'ຊຸດປັບອາກາດໃນຫ້ອງຂັບ' },
  { titleEn: 'SUNROOF ASSY', titleLo: 'ຫຼັງຄາ' },
  { titleEn: 'COLUMN ASSY-STEERING', titleLo: 'ຊຸດແກນພວງມາໄລ' },
  { titleEn: 'MODULE ASSY-STRG WHEEL AIR BAG', titleLo: 'ແອແບັກພວງມາໄລ' },
  { titleEn: 'CURTAIN AIR BAG', titleLo: 'ຖົງແອແບັກເພດານ' },
  { titleEn: 'SIDE A/BAG MODULE-FR', titleLo: 'ຖົງແອແບັກໜ້າຂວາ' },
  { titleEn: 'COVER-RECLINER ASSY FR SEAT (L,R)', titleLo: 'ໂກບມືປັບເບາະໜ້າ ຊ້າຍ-ຂວາ' },
  { titleEn: 'WHEEL ASSY-STEERING', titleLo: 'ວົງພວງມາໄລ' },
  { titleEn: 'SWITCH ASSY-STRG REMOTE CONT', titleLo: 'ສະວິກຄວບຄຸມພວງມາໄລ' },
  { titleEn: 'TILT/TELESCOPIC STEERING WHEEL', titleLo: 'ຊຸດປັບພວງມາໄລຂື້ນ-ລົງ' },
  { titleEn: 'AIR BAG ASSY-PASSENGER', titleLo: 'ແອແບັກຂ້າງຄົນຂັບ' },
  { titleEn: 'CONTACT ASSY-CLOCK SPRING', titleLo: 'ສາຍແພພວງມາໄລ' },
  { titleEn: 'MULTIFUNCTION SWITCH', titleLo: 'ສະວິກເປີດໄຟຕາ' },
  { titleEn: 'TRIM ASSY-FR DR SCUFF LH', titleLo: 'ໂກບຢຽບຂື້ນປະຕູໜ້າ ຊ້າຍ' },
  { titleEn: 'TRIM ASSY-FR DR SCUFF RH', titleLo: 'ໂກບຢຽບຂື້ນປະຕູໜ້າ ຂວາ' },
  { titleEn: 'TRIM ASSY-RR DR SCUFF LH', titleLo: 'ໂກບຢຽບຂື້ນປະຕູຫຼັງ ຊ້າຍ' },
  { titleEn: 'TRIM ASSY-RR DR SCUFF RH', titleLo: 'ໂກບຢຽບຂື້ນປະຕູຫຼັງ ຂວາ' },
  { titleEn: 'TRIM ASSY-CTR PILLAR LWR LH', titleLo: 'ໂກບປົກສາຍເຂັມຂັດຂ້າງ ຊ້າຍ' },
  { titleEn: 'TRIM ASSY-CTR PILLAR LWR RH', titleLo: 'ໂກບປົກສາຍເຂັມຂັດຂ້າງ ຂວາ' },
  { titleEn: 'FRONT SEAT', titleLo: 'ເບາະໜ້າ' },
  { titleEn: '2ND SEAT', titleLo: 'ເບາະທີ 2' },
  { titleEn: '3ND SEAT', titleLo: 'ເບາະທີ 3' },
  { titleEn: '4ND SEAT', titleLo: 'ເບາະທີ 4' },
  { titleEn: 'SEAT MOTOR ASSY', titleLo: 'ມໍເຕີປັບເບາະ' },
  { titleEn: 'MEMORY SEAT', titleLo: 'ສະວີກປັບເບາະໂອໂຕ' },
  { titleEn: 'FLOOR MAT', titleLo: 'ຜ້າປູພື້ນ' },
];

// 하부 점검 항목 이름
export const UnderBodyTitle = [
  { titleEn: 'CARRIER ASSY-SPARE WHEEL', titleLo: 'ຊຸດໂສ້ຫ້ອຍຢາງສະກົ້ວ' },
  { titleEn: 'FRAME ASSY', titleLo: 'ຄັນຊີລົດ' },
  { titleEn: 'CROSSMEMBER', titleLo: 'ເຝມກ້ອງຈັກ' },
  { titleEn: 'CARRIER ASSY-FRONT END MODULE', titleLo: 'ໂຄງຕາໜ້າ (ເຝມໜໍ້ນ້ຳ)' },
  { titleEn: 'COLUMN & SHAFT ASSY-STEERING', titleLo: 'ຊຸດແກນພວງມາໄລ' },
  { titleEn: 'CYLINDER ASSY-BRAKE MASTER', titleLo: 'ແມ່ປ້ຳເບກ' },
  { titleEn: 'BOOSTER ASSY-BRAKE', titleLo: 'ເຕົ້າໄຮໂລວັກ' },
  { titleEn: 'HOSE-BRAKE', titleLo: 'ກະແຕະເບກ' },
  { titleEn: 'ASSY-CLUTCH', titleLo: 'ແຜ່ນຄາດ' },
  { titleEn: 'CYLINDER -CLUTCH', titleLo: 'ກະບອກຄາດ' },
  { titleEn: 'PAN ASSY-ENGINE OIL', titleLo: 'ທ້ອງອ່າງນ້ຳມັນເຄື່ອງ' },
  { titleEn: 'ENGINE ASSY', titleLo: 'ເຄື່ອງຈັກ' },
  { titleEn: 'TRANSMISSION ASSY', titleLo: 'ເຟື່ອງທ້າຍ' },
  { titleEn: 'SHOCK ABSORBER FR(LH)', titleLo: 'ຊົກອັບຫນ້າຊ້າຍ' },
  { titleEn: 'SHOCK ABSORBER FR(RH)', titleLo: 'ຊົກອັບຫນ້າຂວາ' },
  { titleEn: 'SHOCK ABSORBER RR(LH)', titleLo: 'ຊົກອັບຫຼັງ ຊ້າຍ' },
  { titleEn: 'SHOCK ABSORBER RR(RH)', titleLo: 'ຊົກອັບຫຼັງ ຂວາ' },
  { titleEn: 'PUMP ASSY-POWER STEERING', titleLo: 'ປ້ຳພາວເວີ້' },
  { titleEn: 'RESERVOIR ASSY-POWER STEERING', titleLo: 'ຕຸກພັກນ້ຳມັນພາວເວີ້' },
  { titleEn: 'SHAFT ASSY-DRIVE,LH', titleLo: 'ເພົາໜ້າ ຊ້າຍ' },
  { titleEn: 'SHAFT ASSY-DRIVE,RH', titleLo: 'ເພົາໜ້າ ຂວາ' },
  { titleEn: 'SHAFT ASSY-DRIVE REAR,LH', titleLo: 'ເພົາຫຼັງ ຊ້າຍ' },
  { titleEn: 'SHAFT ASSY-DRIVE REAR,RH', titleLo: 'ເພົາຫຼັງ ຂວາ' },
  { titleEn: 'TRANSFER ASSY', titleLo: 'ຊຸດເຟື່ອງທ້າຍ ໂຟວີນ' },
  { titleEn: 'GEAR & LINKAGE ASSY-P/S', titleLo: 'ຊຸດແລັກພວງມາໄລ' },
  { titleEn: 'END ASSY-TIE ROD,LH', titleLo: 'ລູກໝາກຄັນສົ່ງຊ້າຍ' },
  { titleEn: 'END ASSY-TIE ROD,RH', titleLo: 'ລູກໝາກຄັນສົ່ງຂວາ' },
  { titleEn: 'HYDRAULIC MODULE ASSY(ABS)', titleLo: 'ໂມດູ້ນ ABS' },
  { titleEn: 'ARM COMPLETE-FR LWR,LH', titleLo: 'ປີກນົກລຸ່ມໜ້າຊ້າຍ' },
  { titleEn: 'ARM COMPLETE-FR LWR,RH', titleLo: 'ປີກນົກລຸ່ມໜ້າຂວາ' },
  { titleEn: 'DISC-FRONT WHEEL BRAKE', titleLo: 'ຈານດຣິດເບກໜ້າ' },
  { titleEn: 'HUB ASSY-FR WHEEL', titleLo: 'ເບົ້າລູກປືນລໍ້ໜ້າ' },
  { titleEn: 'HUB ASSY-RR WHEEL', titleLo: 'ເບົ້າສູກປືນລໍ້ຫຼັງ' },
  { titleEn: 'CAP ASSY-WHEEL HUB', titleLo: 'ໂກບລໍ້' },
  { titleEn: 'FRONT WHEEL ASSY', titleLo: 'ລໍ້ລົດໜ້າ' },
  { titleEn: 'REAR WHEEL ASSY', titleLo: 'ລໍ້ລົດຫຼັງ' },
  { titleEn: 'CALIPER KIT-BRAKE', titleLo: 'ເຕົ້າດຣິດເບກ' },
  { titleEn: 'PAD KIT-FRONT DISC BRAKE', titleLo: 'ຜ້າເບກໜ້າ' },
  { titleEn: 'CYLINDER ASSY-WHEEL, FR', titleLo: 'ກະບອກເບກໜ້າ' },
  { titleEn: 'CYLINDER ASSY-WHEEL, RR', titleLo: 'ກະບອກເບກຫຼັງ' },
  { titleEn: 'SHOE & LINING KIT-RR BRAKE', titleLo: 'ຜ້າເບກຫຼັງ' },
  { titleEn: 'VALVE ASSY-LSP', titleLo: 'ວາວເບກ' },
  { titleEn: 'BAR ASSY-FR STABILIZER', titleLo: 'ເຫຼັກກັນໂຄ້ງ' },
  { titleEn: 'SHAFT ASSY- PROPELLER', titleLo: 'ກັກດັ້ງ' },
  { titleEn: 'ARM COMPLETE-UPR,LH', titleLo: 'ປີກນົກເທີ່ງ ຊ້າຍ' },
  { titleEn: 'ARM COMPLETE-UPR,RH', titleLo: 'ປີກນົກເທີ່ງ ຂວາ' },
  { titleEn: 'SPRING ASSY-RR SUSP LEAF', titleLo: 'ແໜບ' },
  { titleEn: 'CARRIER ASSY-DIFFERENTIAL', titleLo: 'ໂປ້ງຫຼັງ' },
  { titleEn: 'BEARING & HUB ASSY', titleLo: 'ລູກປືນ ແລະ ເບົ້າລູກປືນ' },
  { titleEn: 'PANEL-UNDER COVER', titleLo: 'ໂກບກ້ອງຈັກ' },
  { titleEn: 'PIPE-TAIL W/MUFFLER', titleLo: 'ທໍ່ໄຟ' },
  { titleEn: 'BRACKET ASSY-ENGINE MTG', titleLo: 'ຢາງຕີນຈັກ' },
  { titleEn: 'BRACKET ASSY-T/M MTG', titleLo: 'ຢາງຕີນເກຍ' },
  { titleEn: 'VACUUM BRAKE PRESSURE ASSY', titleLo: 'ເຕົ້າລົມເບກ' },
  { titleEn: 'FUEL TANK', titleLo: 'ຖັງນ້ຳມັນ' },
  { titleEn: 'LEAKAGE POINT', titleLo: 'ກວດເຊັກນ້ຳ-ນ້ຳມັນເຄື່ອງ-ນ້ຳມັນເກຍຍ້ອຍ' },
  { titleEn: 'TIRE FR, LH', titleLo: 'ຢາງໜ້າ ຊ້າຍ' },
  { titleEn: 'TIRE FR, RH', titleLo: 'ຢາງໜ້າ ຂວາ' },
  { titleEn: 'TIRE RR, LH', titleLo: 'ຢາງຫຼັງ ຊ້າຍ' },
  { titleEn: 'TIRE RR, RH', titleLo: 'ຢາງຫຼັງ ຂວາ' },
];

// 엔진 점검 항목 이름
export const EngineTitle = [
  { titleEn: 'BATTERY', titleLo: 'ໝໍ້ໄຟ' },
  { titleEn: 'ELECTRIC WIRE', titleLo: 'ສາຍຫົວໝໍ້ໄຟ' },
  { titleEn: 'TRAY ASSY-BATTERY', titleLo: 'ເຮືອນໝໍ້ໄຟ' },
  { titleEn: 'CLEANER ASSY-AIR', titleLo: 'ກອງອາກາດຈັກ' },
  { titleEn: 'SENSOR ASSY-AIR FLOW', titleLo: 'ເຊັນເຊີແອໂຟ' },
  { titleEn: 'BODY ASSY-THROTTLE', titleLo: 'ເຮືອນປີກແມ່ນກະເບື້ອ' },
  { titleEn: 'COIL ASSY-IGNITION', titleLo: 'ຄອຍຈຸດລະເບີດ' },
  { titleEn: 'MANIFOLD ASSY-INTAKE', titleLo: 'ທໍ່ຮ່ວມໄອດີ' },
  { titleEn: 'RAIL ASSY-FUEL LEAKAGE', titleLo: 'ກວດນ້ຳມັນຊື່ມຢູ່ກ້ອງຈັກ' },
  { titleEn: 'PUMP ASSY-COOLANT', titleLo: 'ປ້ຳນ້ຳ' },
  { titleEn: 'COVER ASSY-ROCKER', titleLo: 'ຝາຄອບວາວ' },
  { titleEn: 'BELT- V', titleLo: 'ສາຍພານນອກ' },
  { titleEn: 'IDLE BEARING', titleLo: 'ລູກປືນສາຍພານ' },
  { titleEn: 'TENSIONER ASSY', titleLo: 'ໂຕເຄັງສາຍພານ' },
  { titleEn: 'PULLEY-DAMPER', titleLo: 'ມໍເລ້ຄໍຫວ່ຽງ' },
  { titleEn: 'RADIATOR ASSY', titleLo: 'ໝໍ້ນ້ຳ' },
  { titleEn: 'COOLANT', titleLo: 'ນ້ຳຢາໝໍ້ນ້ຳ' },
  { titleEn: 'SHROUD-RADIATOR', titleLo: 'ອູ້ມລົມໝໍ້ນ້ຳ' },
  { titleEn: 'MOTOR-RADIATOR COOLING FAN', titleLo: 'ພັດລົມໝໍ້ນ້ຳ (ໄຟຟ້າ)' },
  { titleEn: 'FAN-COOLING', titleLo: 'ພັດລົມຈັກ' },
  { titleEn: 'BLOWER ASSY-CONDERSER', titleLo: 'ພັດລົມແຜງຮ້ອນແອ' },
  { titleEn: 'CONDERSER ASSY', titleLo: 'ແຜງຮ້ອນແອ' },
  { titleEn: 'GENERATOR ASSY', titleLo: 'ໃດສາກ' },
  { titleEn: 'COMPRESSOR ASSY', titleLo: 'ຄອມແອ' },
  { titleEn: 'STARTER ASSY', titleLo: 'ໃດສະຕາດ' },
  { titleEn: 'TURBOCHARGER ASSY', titleLo: 'ເທີໂບ' },
  { titleEn: 'PUMP ASSY-HIGH PRESSURE', titleLo: 'ປ້ຳຄອມມອນເລວ' },
  { titleEn: 'PUMP ASSY INJECTION', titleLo: 'ປ້ຳກາຊັວນ' },
  { titleEn: 'FUEL PUMP', titleLo: 'ປ້ຳແຢ໋ກ' },
  { titleEn: 'FILTER-FUEL', titleLo: 'ກອງກາຊັວນ' },
  { titleEn: 'INTER COOLER', titleLo: 'ແຜງອີນເຕີຄູເລີ' },
  { titleEn: 'RESERVOIR & PUMP ASSY-WASHER', titleLo: 'ຕຸກສີດນ້ຳລ້າງແວ່ນ' },
  { titleEn: 'RESERVOIR ASSY RADIATOR', titleLo: 'ຕຸກພັກນ້ຳໝໍ້ນ້ຳ' },
  { titleEn: 'PANEL ASSY-COWL(WHEEL HOUSE)', titleLo: 'ໂກບຫົວຊົກອັບໜ້າ' },
  { titleEn: 'MEMBER ASSY-FRONT SIDE,LH', titleLo: 'ໂກບຂ້າງຈັກ ຊ້າຍ' },
  { titleEn: 'MEMBER ASSY-FRONT SIDE,RH', titleLo: 'ໂກບຂ້າງຈັກ ຂວາ' },
  { titleEn: 'STALL TEST(A/T)', titleLo: 'ກະປຸກເກຍໂອໂຕ້' },
  { titleEn: 'HARD TOP((PICK-UP)', titleLo: 'ຊຸດເສີມຫຼັງຄາກະບະ' },
  { titleEn: 'HANDLE ASS-LOCK (BRAKET & ASSEMBLY)', titleLo: 'ຢາງຮອງຫົວເກັງ' },
  { titleEn: 'BRACKET-FR CAB MTG', titleLo: 'ກວດຫົວລົດຈີກ(ແຕກ)' },
  { titleEn: 'WHEEL ALIGNMENT', titleLo: 'ຂີ່ລົດລອງເບີ່ງພວງມາໄລ,ຊື່ບໍ່,ຈ່ອງຊ້າຍ-ຈ່ອງຂວາບໍ່' },
  { titleEn: 'INTERIOR NOISE', titleLo: 'ຂີ່ລົດລອງເບີ່ງສຽງດັງທາງໃນ' },
  { titleEn: 'OUTSIDE NOISE', titleLo: 'ຂີ່ລົດລອງເບີ່ງສຽງດັງທາງນອກ' },
];

export class CarInspection {
  @IsUUID()
  adminId: string;
  @IsUUID()
  usedCarStockId: string;
  @IsNumber()
  exteriorPassed: number = 0;
  @IsNumber()
  interiorPassed: number = 0;
  @IsNumber()
  underbodyPassed: number = 0;
  @IsNumber()
  enginePassed: number = 0;
  @ValidateNested()
  @Type(() => CarInspectionItem)
  exteriorChecklist: CarInspectionItem[];
  @ValidateNested()
  @Type(() => CarInspectionItem)
  interiorChecklist: CarInspectionItem[];
  @ValidateNested()
  @Type(() => CarInspectionItem)
  underbodyChecklist: CarInspectionItem[];
  @ValidateNested()
  @Type(() => CarInspectionItem)
  engineChecklist: CarInspectionItem[];
}

class CarInspectionItem {
  @IsNumber()
  no: number;
  @IsOptional()
  status: CarInspectionItemStatus = null;
  @IsString()
  titleEn: string;
  @IsString()
  titleLo: string;
  @IsString({ each: true })
  photos: string[];
  @IsOptional()
  remark?: string;
}

export enum CarInspectionItemStatus {
  PASS = 'Pass',
  NORMAL = 'Normal',
  BAD = 'Bad',
}
